apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: node-selector-demo
spec:
  containers:
  - name: my-container
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd